### ISSUE TITLE
I have private pods used in my project so pod install fails. 

### ISSUE THREAD

**Issue by manivel-nagarajan** [ty0x2333/cocoapods-action#4]
My workflow fails while `pod install`, since I have private pods in my profile and we use ssh authentication. Any plans to support this?

Thanks in advance.

**Comment by ty0x2333** [comment]
@manivel-nagarajan 

If you try to install a private Pod on another account, then you need access rights for that account.

You can try this action: https://github.com/webfactory/ssh-agent

Add it before `ty0x2333/cocoapods-action`.

**Comment by manivel-nagarajan** [comment]
Thanks @ty0x2333
